### ISSUE TITLE
Too much space used

### ISSUE THREAD

**Issue by Latz** [swissspidy/oEmbed-API#163] opened 2015-10-01 12:03 UTC
If you're embedding a small post,  too much space is used:

![ombed2](https://cloud.githubusercontent.com/assets/633642/10220127/1741500e-6845-11e5-9f66-1b09af68ead1.png)

**Comment by swissspidy** [comment] 2015-10-01 12:38
Seems like the resizing is not working. Probably a duplicate of #164

**Closed** 2015-10-01 14:13 UTC
