### ISSUE TITLE
Support Right To Left (RTL) text direction

### ISSUE THREAD

**Issue by kanenas** [swissspidy/oEmbed-API#67] opened 2015-09-11 10:29 UTC
Although I have no problems with <strong>Greek</strong> & <strong>Cyrillic</strong> characters see the example http://www.my-soul.net/blog/%D0%B8%D1%85-%D0%B4%D0%B2%D0%B5-%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%B8-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC/ when it comes to count the <strong>Arabic</strong> characters I have this (see the image attached)...

![oembed-api-counting-arabic-characters](https://cloud.githubusercontent.com/assets/327786/9812819/c1e2fdc2-5888-11e5-96db-1483fb31b1f6.jpg)

http://www.my-soul.net/blog/%CE%B1%CE%BA%CE%BF%CF%8D%CF%83%CE%B5%CE%B9-%CE%B4%CE%B9%CE%B1%CF%83%CF%86%CE%B1%CE%BB%CE%AF%CE%B6%CE%B5%CF%84%CE%B1%CE%B9-%CE%BC%CE%B5%CF%84%CE%B1%CE%B3%CE%BB%CF%89%CF%84%CE%B9%CF%83%CF%84%CE%AE%CF%82/
Don't ask what it says... I have no idea :)

**Comment by kanenas** [comment] 2015-09-11 10:36
Maybe it has something to do with not using RTL!?

**Comment by swissspidy** [comment] 2015-09-11 10:43
I have no idea what it says either but  it's great that you're testing it ;)

We're using the same method as WordPress 4.3 for counting, see https://github.com/swissspidy/oEmbed-API/blob/master/includes/template.php#L26-L34 for an explanation.

Basically, the word count type needs to be translated by the different locales. So far there haven't been any translations for the plugin, that's why it probably doesn't work.

I just removed the text domain from the `_x( 'words', 'Word count type. Do not translate!' )` call so it should use the translations of WordPress, not the plugin. In other words: Download the current version here from GitHub to see if something has changed.

Again, counting depends on the currently active language on your site. Mixing multiple languages in one post can lead to an incorrect count.

**Comment by kanenas** [comment] 2015-09-11 11:07
Nothing changed :(

**Comment by kanenas** [comment] 2015-09-11 11:21
OK, this is funny :)
I switched the <strong>Site Language</strong> from <strong>English (United States)</strong> to <strong>العربية</strong> (...not sure what this is) and here is the screenshot...

![oembed-api-01](https://cloud.githubusercontent.com/assets/327786/9813645/26e39a2c-5890-11e5-894d-01adaed19457.jpg)

but, as you said it messes up all the others...

![oembed-api-02](https://cloud.githubusercontent.com/assets/327786/9813665/4778b722-5890-11e5-9887-551accd3ed45.jpg)

**Comment by kanenas** [comment] 2015-09-11 11:25
Doesn't this``` <meta charset="UTF-8">``` matter? Maybe using some mb... stuff http://php.net/manual/en/book.mbstring.php ?!

**Comment by swissspidy** [comment] 2015-09-11 11:52
No, `<meta charset="UTF-8">` doesn't matter here. Counting is done on the server side.

As I said before, we're using the same method as WordPress 4.3 for counting. However, I just detected that I somehow implemented only half of that... I'll fix that right away together with #66

**Comment by kanenas** [comment] 2015-09-11 12:09
:+1:

**Comment by swissspidy** [comment] 2015-09-12 10:33
As you can see from the commits above I made various improvements to RTL support.

The last one adds so-called LRM (left-to-right mark) character after the closing parenthesis of the word count. This should fix the effect you showed in the initial screenshot.

Core uses this technique in exactly one place, as far as I can see: the sample permalink display when editing a post.

@kanenas Please let me know how things look now on your site.

**Comment by kanenas** [comment] 2015-09-12 18:56
@swissspidy, here are a few test that I just made with the latest version:

<strong>Site Language</strong>: English (United States) or Greek
![oembed-api-us-arabic-01](https://cloud.githubusercontent.com/assets/327786/9833242/92326700-5998-11e5-8584-1bd8e85c6e0e.jpg)

![oembed-api-greek-arabic-01](https://cloud.githubusercontent.com/assets/327786/9833245/9ba64e00-5998-11e5-896c-f853d311161e.jpg)

or you can check it out yourself here http://www.my-soul.net/blog/%CE%B1%CE%BA%CE%BF%CF%8D%CF%83%CE%B5%CE%B9-%CE%B4%CE%B9%CE%B1%CF%83%CF%86%CE%B1%CE%BB%CE%AF%CE%B6%CE%B5%CF%84%CE%B1%CE%B9-%CE%BC%CE%B5%CF%84%CE%B1%CE%B3%CE%BB%CF%89%CF%84%CE%B9%CF%83%CF%84%CE%AE%CF%82/ (right now site's language is <strong>Greek</strong>)

<strong>Site Language</strong>: العربية (btw this means Arabic)

![oembed-api-arabic-greek-01](https://cloud.githubusercontent.com/assets/327786/9833253/b3a96974-5998-11e5-8d8c-54e848b99b17.jpg)
![oembed-api-arabic-russian-01](https://cloud.githubusercontent.com/assets/327786/9833254/b3ad1dbc-5998-11e5-8784-312853df29b1.jpg)

Tell me if you need more tests!

**Comment by swissspidy** [comment] 2015-09-12 19:19
Thanks a ton!

I think your third example is the most realistic one as the post content matches site language. Otherwise the browser gets confused.

I'm reading more and more about text direction stuff and all I can find about parenthesis and RTL languages is that this is somewhat _expected behaviour_, even though it might look strange to us. For reference:

http://www.i18nguy.com/markup/right-to-left.html
http://stackoverflow.com/questions/5801820/how-to-solve-bidi-bracket-problem

> Parentheses and square brackets do not have an inherent direction. The open parenthesis is between LTR and RTL text runs and so cannot "inherit" the direction of the surrounding text. It therefore defaults to the RTL base direction of the paragraph [...]

> Note that the open parenthesis is rendered "mirror-imaged". That is, it looks like a closing parenthesis in English. Parentheses and Square Brackets, and some other characters, are displayed as mirror-images (i.e. reversed) when the text direction is right-to-left. This is because the characters have the semantics of open and close, not the graphically left and right. An open parenthesis or square bracket, in right-to-left text, is rendered as a mirror-image so that it visually encloses the text to its left. Similarly, closing parentheses and brackets are also mirror-imaged, so they face the text to their right.

**Comment by kanenas** [comment] 2015-09-14 14:24
@swissspidy, this is more complicated than I thought :)
So, here is what I can do for you.
I have changed my "Site Language" to العربية so you can embed in your test website this post http://www.my-soul.net/blog/%D9%82%D8%AF-%D8%AF%D9%81%D9%91%D8%A9-%D8%A7%D9%84%D8%B9%D8%AF%D9%91-%D8%A8%D9%88%D8%B2%D9%8A%D8%B1%D9%87%D8%A7-%D9%83%D9%85%D8%A7-%D8%A8%D9%80-%D9%88%D8%AA%D9%86%D8%A7%D9%85%D8%AA-%D8%A7%D9%84%D8%AE/ 

 Also, I have used parenthesis on the blog post's title and on the first line of the blog's content.
Hope it helps!

**Comment by swissspidy** [comment] 2015-09-15 09:09
@kanenas Thank you very much!

I hope the problem occurs because the word count is in English and the rest is Arabic and that a proper translation would solve this — or this is actually expected behaviour.

I'll try to ping some Arabic translation editors for core about this.

**Comment by kanenas** [comment] 2015-09-15 09:39
:+1:

**Comment by swissspidy** [comment] 2015-09-15 10:49
So I've learned that the parentheses are really only displayed wrong because of the lacking translation.

#93 fixes the problem for me

**Comment by kanenas** [comment] 2015-09-15 11:23
Cool! Where can I download the <strong>Arabic (Marocco)</strong> translations?

**Comment by kanenas** [comment] 2015-09-15 11:25
Oops... never mind I have found the branch!

**Comment by kanenas** [comment] 2015-09-15 12:24
I can confirm that the problem is fixed for me too!

![oembed-api-arabic-01](https://cloud.githubusercontent.com/assets/327786/9876305/c3fbc26e-5bbd-11e5-8c0d-5cc0cd022873.jpg)

**Closed** 2015-09-15 12:43 UTC
Labels: Bug

**Comment by ramiy** [comment] 2015-09-17 09:36
http://imgur.com/a/boxUO

**Comment by swissspidy** [comment] 2015-09-17 09:41
@ramiy uhm, thanks for these screenshots. What do you wanna express with them?

**Comment by ramiy** [comment] 2015-09-21 21:49
That it's working as expected!
